#!/bin/sh
### BEGIN INIT INFO
# Provides:             Durex
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    print user name
# Description:          print user name
### END INIT INFO

. /lib/lsb/init-functions

PATH='/sbin:/bin'
RETVAL=0
NAME=Durex
DAEMON=/bin/$NAME
SCRIPTNAME=/etc/init.d/$NAME

start() {
	[ -f /var/lock/Durex.lock ] && exit 0
	touch /var/lock/Durex.lock
	start_daemon /bin/Durex
	RETVAL=$?
	return $RETVAL
}

stop() {
	[ -f /var/lock/Durex.lock ] || exit 0
	# pkill send SIGTERM signal by default
	killproc Durex
	RETVAL=$?
	/bin/rm /var/lock/Durex.lock
	return $RETVAL
}

rhstatus() {
	status_of_proc Durex
	RETVAL=$?
	return $RETVAL
}

restart() {
	stop
	start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|force-reload)
    restart
  ;;
  status)
    rhstatus
  ;;
  reload|try-restart)
    log_warning_msg "Action '$1' is meaningless for this init script"
    exit 0
  ;;
*)
  log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
  exit 1
esac
